# NumPy

### Theory



In [ ]:
# What is numPy:

# Library used for scientific computing
# main datatype is numpy array , used to store numbers.
# used ofr mathematics related work
# all other librarries based on numpy
# written in c
# python core library
# need of numpy -> all python inbuilt datatypes are slow that why we needed numpy

In [ ]:
# What is numpy?
# NumPy is the fundamental package for scientific computing in Python.
#  It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices),
# and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
# At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

In [ ]:
# Numpy Arrays Vs Python Sequences
# NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

# The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

# NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

# A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating NumPy array

In [2]:
import numpy as np

In [ ]:
# FIRST WAY TO CREATE ARRAY

In [ ]:
# 1D array(vetcor)
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D(matrix) and 3D(tensor)

#you can create multiple nd tensor or arrays
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))


d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d)
print(type(d))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [ ]:
# dtype
# this parameter is appliable on all ways of creating array

# can any datatype, you can make array
c = np.array([1,2,3],dtype=float)
print(c)

[1. 2. 3.]


In [ ]:
# SECOND WAY TO CREATE ARRAY

In [ ]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# reshape

In [ ]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# THIRD WAY
# in DL used to initialize things like weight

In [ ]:
#np.ones
# intitalize all items as 1
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#np.zeros
# intitalize all items as 0
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#np.random()
# intitalize all items randomly b/w 0 and 1

np.random.random((3,3)) # range b/w 0 to 1

array([[0.37939711, 0.5708381 , 0.86590124],
       [0.99369698, 0.82530566, 0.75233195],
       [0.72327621, 0.38538606, 0.50827016]])

In [ ]:
#np.linspace(linear space)
# gives points at same distance

np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [ ]:
# np.identity
#(create identity matrix)

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Attributes:

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1,a2,a3,sep='\n\n')

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim
# tells no of dimensions of array

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
# shape
# tell total no items in each dimension

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
# size
#tells total of items in array

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
# itemsize
# tells how much each item will take space in memory
# int32 = 4 bytes , int64 = 8 bytes

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [ ]:
# dtype
# tells dtypes of each item in array

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing dtype

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
# used to reduce memory size
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
# scalar operations
# operations on single array by a scalar(single number)

In [ ]:
# arithemetic operations
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a1 - 1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [ ]:
a1 * 4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [ ]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
a1 % 4

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
a1 **2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational operations

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a2 == 14

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 != 23

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [ ]:
a2 > 14

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 < 17

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 >=13

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 <=19

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [ ]:
# vector operations
# operations between two arrays
# each element of one array maps with each element of enother array
# shape must be same

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# arithemetic operator

In [ ]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [ ]:
a1 % a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [ ]:
# realtional operations

In [ ]:
a1 == a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1 != a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a1 > a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1 < a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a1 >= a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1 <= a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[75., 97., 87.],
       [79., 42., 89.],
       [54., 74., 59.]])

In [ ]:
#max/min/sum/prod

In [ ]:
print(np.max(a1))

97.0


In [ ]:
print(np.min(a1))

42.0


In [ ]:
print(np.sum(a1))

656.0


In [ ]:
print(np.prod(a1))

4.40652389822694e+16


In [ ]:
# you can do it by columns and row wise
# axis = 0 -> column
# axis = 1 -> row

In [ ]:
print(np.max(a1,axis=1))

[97. 89. 74.]


In [ ]:
print(np.sum(a1,axis=1))

[259. 210. 187.]


In [ ]:
print(np.min(a1,axis=1))

[75. 42. 54.]


In [ ]:
print(np.prod(a1,axis=1))

[632925. 295302. 235764.]


In [ ]:
#mean/median/std/var
# same you can do it column or row wise

In [ ]:
print(np.mean(a1))

72.88888888888889


In [ ]:
print(np.median(a1))

75.0


In [ ]:
print(np.std(a1))

16.953822541404403


In [ ]:
print(np.var(a1))

287.4320987654321


In [ ]:
print(np.mean(a1,axis = 0))

[69.33333333 71.         78.33333333]


In [ ]:
print(np.mean(a1,axis = 1))

[86.33333333 70.         62.33333333]


In [ ]:
# log and exponential

In [ ]:
print(np.log(a1))

[[4.31748811 4.57471098 4.46590812]
 [4.36944785 3.73766962 4.48863637]
 [3.98898405 4.30406509 4.07753744]]


In [ ]:
print(np.exp(a1))

[[3.73324200e+32 1.33833472e+42 6.07603023e+37]
 [2.03828107e+34 1.73927494e+18 4.48961282e+38]
 [2.83075330e+23 1.37338298e+32 4.20121040e+25]]


In [ ]:
# dot product

In [ ]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [ ]:
print(np.dot(a2,a3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [ ]:
# trigonometric function
# you never gone to use it

In [ ]:
d = (np.sin(a1))

In [ ]:
print(d)

[[-0.38778164  0.37960774 -0.82181784]
 [-0.44411267 -0.91652155  0.86006941]
 [-0.55878905 -0.98514626  0.63673801]]


In [ ]:
#round/floor/seil

In [ ]:
# round
# value's decimal > 5 then next num otherwise previus num
print(np.round(d))

[[-0.  0. -1.]
 [-0. -1.  1.]
 [-1. -1.  1.]]


In [ ]:
# floor
# always previous num
print(np.floor(d))

[[-1.  0. -1.]
 [-1. -1.  0.]
 [-1. -1.  0.]]


In [ ]:
# floor
# always next num
print(np.ceil(d))

[[-0.  1. -0.]
 [-0. -0.  1.]
 [-0. -0.  1.]]


### Indexing and slicing

In [3]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [4]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
# 1d
# normal

In [7]:
a1[0]

np.int64(0)

In [8]:
a1[-1]

np.int64(9)

In [10]:
a1[2:6]

array([2, 3, 4, 5])

In [11]:
# 2d

In [12]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2[0]

array([0, 1, 2, 3])

In [14]:
a2[0:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a2[1,2]

np.int64(6)

In [16]:
a2[2,1]

np.int64(9)

In [19]:
a2[0:2,2:]

array([[2, 3],
       [6, 7]])

In [20]:
a2[0::2,1:3]

array([[ 1,  2],
       [ 9, 10]])

In [22]:
a2[1,1:3]

array([5, 6])

In [23]:
#3d
# first find kaunse 2d me aayega then follow 2d wala process

In [18]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
a3[1,1,0]

np.int64(6)

### Iterating

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 1D
# Sare items print honge!
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 1D
# Sare rows print honge!
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3 = np.arange(27).reshape(3,3,3)

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#3D
# sare 2d marix print honge!

for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# agar 3d me ya nd me har ek item pe loop chalana ho to

In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3.reshape(9,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
# transpose
# take transpose of matrix

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
#convert any dimension to 1D

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
## In python after running code/cell if output is visible then then they are temporary changes ,else they are permanant changes.

### Staking

In [ ]:
# shape must be same
# it will make changes in original array

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# horizontal staking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical staking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Spliting

In [ ]:
# opposite of staking
# must be equal division

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
np.hsplit(a4,3)

ValueError: array split does not result in an equal division

In [ ]:
# vertical spliting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]