#### np.sort()

In [ ]:
# returns a sorted numpy array

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(1,100,15)
a

array([86, 43, 10, 33, 28, 82,  6, 22, 84, 64, 89, 50, 22, 56, 14])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[13, 36, 89, 96],
       [98, 55, 72, 80],
       [10, 64, 28, 45],
       [25, 79, 46, 34],
       [82, 41, 35, 25],
       [52, 93, 82, 96]])

In [ ]:
np.sort(a) # ascending

array([ 6, 10, 14, 22, 22, 28, 33, 43, 50, 56, 64, 82, 84, 86, 89])

In [ ]:
np.sort(a)[::-1] # descending

array([89, 86, 84, 82, 64, 56, 50, 43, 33, 28, 22, 22, 14, 10,  6])

In [ ]:
np.sort(b) # by default row wise

array([[13, 36, 89, 96],
       [55, 72, 80, 98],
       [10, 28, 45, 64],
       [25, 34, 46, 79],
       [25, 35, 41, 82],
       [52, 82, 93, 96]])

In [ ]:
np.sort(b,axis = 0) # column wise

array([[10, 36, 28, 25],
       [13, 41, 35, 34],
       [25, 55, 46, 45],
       [52, 64, 72, 80],
       [82, 79, 82, 96],
       [98, 93, 89, 96]])

#### np.append()

In [ ]:
# add item at last

In [ ]:
a

array([86, 43, 10, 33, 28, 82,  6, 22, 84, 64, 89, 50, 22, 56, 14])

In [ ]:
np.append(a,200)

array([ 86,  43,  10,  33,  28,  82,   6,  22,  84,  64,  89,  50,  22,
        56,  14, 200])

In [ ]:
b

array([[13, 36, 89, 96],
       [98, 55, 72, 80],
       [10, 64, 28, 45],
       [25, 79, 46, 34],
       [82, 41, 35, 25],
       [52, 93, 82, 96]])

In [ ]:
np.append(b,np.ones((6,1)))

array([13., 36., 89., 96., 98., 55., 72., 80., 10., 64., 28., 45., 25.,
       79., 46., 34., 82., 41., 35., 25., 52., 93., 82., 96.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[13., 36., 89., 96.,  1.],
       [98., 55., 72., 80.,  1.],
       [10., 64., 28., 45.,  1.],
       [25., 79., 46., 34.,  1.],
       [82., 41., 35., 25.,  1.],
       [52., 93., 82., 96.,  1.]])

In [ ]:
b[0]

array([13, 36, 89, 96])

In [ ]:
b.shape[0]

6

#### np.concatenate()

In [ ]:
# joins two arrays horiizontaly/vertically
# exact work like staking

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [ ]:
c,d

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [ ]:
# row wise
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# column wise
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

#### np.unique()

In [ ]:
e = np.array([1,1,1,1,2,2,2,2,3,3,3,4,4,4,4,5,5,5,6,6,6,7])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
f = np.arange(20).reshape(5,4)

In [ ]:
np.unique(f)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### np.expand_dims()

In [ ]:
# convert 1d to 2d or 2d to 3d that means nd to n+1d

In [ ]:
a = np.arange(6)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.expand_dims(a,axis=0) # also known as row vectorization

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
np.expand_dims(a,axis=1) # column vectorization

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

#### np.where()

In [ ]:
# it returns indices of all that elements which satisifes the condition
# np.where(condition,true,false)
# by using this function you can write very powerful logics

In [ ]:
g = np.arange(20)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.where(g>10)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),)

In [ ]:
h = np.random.randint(1,100,25)
h

array([92, 49, 83, 59, 60,  5, 27, 88,  5,  1, 68, 72, 47, 35, 10, 22, 74,
       17, 86, 95, 12, 83,  2, 94, 77])

In [ ]:
np.where(h % 2==0,0,h)

array([ 0, 49, 83, 59,  0,  5, 27,  0,  5,  1,  0,  0, 47, 35,  0,  0,  0,
       17,  0, 95,  0, 83,  0,  0, 77])

#### np.argsmax()

In [ ]:
# gives the index of maximum number in array
# mostly uses with 1d array

In [ ]:
i = np.random.randint(1,50,25)
i

array([13, 12,  4, 13,  1, 15, 25,  7, 35, 30,  4, 45, 10, 19,  6, 13, 16,
       15, 46, 27, 46, 48, 13, 28, 49])

In [ ]:
np.max(i)

np.int64(49)

In [ ]:
np.argmax(i)

np.int64(24)

In [ ]:
j = np.random.randint(1,40,20).reshape(5,4)

In [ ]:
j

array([[ 9, 13, 21, 17],
       [23, 27,  7,  2],
       [10, 32, 33, 14],
       [24, 13, 37, 12],
       [22, 30, 29, 18]])

In [ ]:
np.argmax(j)

np.int64(14)

In [ ]:
np.argmax(j,axis =0)

array([3, 2, 3, 4])

In [ ]:
np.argmax(j,axis =1)

array([2, 1, 2, 2, 1])

#### np.argmin()

In [ ]:
# same working as argmax
# work on smallest number

In [ ]:
i

array([13, 12,  4, 13,  1, 15, 25,  7, 35, 30,  4, 45, 10, 19,  6, 13, 16,
       15, 46, 27, 46, 48, 13, 28, 49])

In [ ]:
np.argmin(i)

np.int64(4)

In [ ]:
j

array([[ 9, 13, 21, 17],
       [23, 27,  7,  2],
       [10, 32, 33, 14],
       [24, 13, 37, 12],
       [22, 30, 29, 18]])

In [ ]:
np.argmin(j,axis=1)

array([0, 3, 0, 3, 3])

In [ ]:
np.argmin(j,axis=0)

array([0, 0, 1, 1])

In [ ]:
np.argmin(j)

np.int64(7)

#### np.cumsum() and np.cumprod()

In [ ]:
# used to calculate cumulative sum/product

In [ ]:
k = np.linspace(1,30,14)
k =np.round(k).reshape(7,2)

In [ ]:
h= np.random.random(10)

In [ ]:
h

array([0.77601205, 0.6382201 , 0.06393505, 0.88952448, 0.51254541,
       0.30420646, 0.61878719, 0.67384241, 0.53323932, 0.49069195])

In [ ]:
i = np.random.randint(1,20,5)
i

array([12,  8,  6,  7,  5])

In [ ]:
np.cumsum(i)

array([12, 20, 26, 33, 38])

In [ ]:
k

array([[ 1.,  3.],
       [ 5.,  8.],
       [10., 12.],
       [14., 17.],
       [19., 21.],
       [23., 26.],
       [28., 30.]])

In [ ]:
np.cumsum(k)

array([  1.,   4.,   9.,  17.,  27.,  39.,  53.,  70.,  89., 110., 133.,
       159., 187., 217.])

In [ ]:
np.cumsum(k,axis=0)

array([[  1.,   3.],
       [  6.,  11.],
       [ 16.,  23.],
       [ 30.,  40.],
       [ 49.,  61.],
       [ 72.,  87.],
       [100., 117.]])

In [ ]:
np.cumsum(k,axis=1)

array([[ 1.,  4.],
       [ 5., 13.],
       [10., 22.],
       [14., 31.],
       [19., 40.],
       [23., 49.],
       [28., 58.]])

In [ ]:
# np.cumprod()

In [ ]:
l=np.arange(10)

In [ ]:
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.cumprod(l)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
m = np.arange(20).reshape(4,5)

In [ ]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.cumprod(m)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.cumprod(m,axis = 0)

array([[   0,    1,    2,    3,    4],
       [   0,    6,   14,   24,   36],
       [   0,   66,  168,  312,  504],
       [   0, 1056, 2856, 5616, 9576]])

In [ ]:
np.cumprod(m,axis = 1)

array([[      0,       0,       0,       0,       0],
       [      5,      30,     210,    1680,   15120],
       [     10,     110,    1320,   17160,  240240],
       [     15,     240,    4080,   73440, 1395360]])

#### np.percentile()

In [ ]:
# tells kitne log us no se piche hain
# ex] 25 percentile means 25 % log usse piche hain.

In [ ]:
m = np.arange(30)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.percentile(m,100) # gives max number

np.float64(29.0)

In [ ]:
np.percentile(m,0) # gives min number

np.float64(0.0)

In [ ]:
np.percentile(m,50) # gives median

np.float64(14.5)

In [ ]:
np.median(m)

np.float64(14.5)

In [ ]:
np.percentile(m,75)

np.float64(21.75)

In [ ]:
n = np.arange(20).reshape(4,5)

In [ ]:
n

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.percentile(n,100)

np.float64(19.0)

In [ ]:
np.percentile(n,40)

np.float64(7.6000000000000005)

In [ ]:
np.percentile(n,100,axis =0)

array([15., 16., 17., 18., 19.])

#### np.histogram()

In [ ]:
# gives frequency count

In [ ]:
 p = np.random.randint(1,100,10)
 p

array([ 2, 75,  7, 74, 61, 26, 86, 99, 13,  2])

In [ ]:
np.histogram(p,bins=[1,10,20,30,40,50,60,70,80,90,200])

(array([3, 1, 1, 0, 0, 0, 1, 2, 1, 1]),
 array([  1,  10,  20,  30,  40,  50,  60,  70,  80,  90, 200]))

#### np.corrcoef()

In [ ]:
# correlation coefficient
# calculates karl pearsons coeficient of corelation
# range b/w 0 to 1
# 0 = no corelation

In [ ]:
salary = np.array([15000,20000,38000,44000,59000])
age = np.array([1,2,3,4,5])

In [ ]:
np.corrcoef(salary,age)

array([[1.        , 0.98579939],
       [0.98579939, 1.        ]])

#### np.isin()

In [ ]:
# used to find multiple elements in array

In [ ]:
q = np.random.randint(1,100,50)

In [ ]:
q

array([85, 65, 28, 61, 82, 92, 25, 56, 36, 72, 40, 77, 83, 77, 46, 56, 76,
       84,  6, 11, 42, 24, 44, 42, 80, 40, 14, 76, 64, 28, 40, 17,  7, 93,
       79, 58, 89, 71, 59, 73, 82, 95, 73, 69, 64, 77, 72, 22, 59, 22])

In [ ]:
np.isin(q,[10,20,30,40,50,60,70,80,90,100])

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [ ]:
# elements
q[np.isin(q,[10,20,30,40,50,60,70,80,90,100])]

array([40, 80, 40, 40])

In [ ]:
r = q[np.isin(q,[10,20,30,40,50,60,70,80,90,100])]

In [ ]:
# index
np.where(np.isin(q,[10,20,30,40,50,60,70,80,90,100]))

(array([10, 24, 25, 30]),)

#### np.flip()

In [ ]:
# reverse the array

In [ ]:
s = np.random.randint(1,200,20)

In [ ]:
s

array([  4, 105,  18, 188,  23,  94,   6, 106, 165, 180, 125,  69, 113,
       196, 120,  93,  95, 151,  58, 185])

In [ ]:
np.flip(s)

array([185,  58, 151,  95,  93, 120, 196, 113,  69, 125, 180, 165, 106,
         6,  94,  23, 188,  18, 105,   4])

In [ ]:
# 2d

In [ ]:
s = s.reshape(4,5)

In [ ]:
s

array([[  4, 105,  18, 188,  23],
       [ 94,   6, 106, 165, 180],
       [125,  69, 113, 196, 120],
       [ 93,  95, 151,  58, 185]])

In [ ]:
# if you don't specify row or column then it will flip both cominely.
np.flip(s)

array([[185,  58, 151,  95,  93],
       [120, 196, 113,  69, 125],
       [180, 165, 106,   6,  94],
       [ 23, 188,  18, 105,   4]])

In [ ]:
np.flip(s,axis =0)

array([[ 93,  95, 151,  58, 185],
       [125,  69, 113, 196, 120],
       [ 94,   6, 106, 165, 180],
       [  4, 105,  18, 188,  23]])

In [ ]:
np.flip(s,axis=1)

array([[ 23, 188,  18, 105,   4],
       [180, 165, 106,   6,  94],
       [120, 196, 113,  69, 125],
       [185,  58, 151,  95,  93]])

#### np.put()

In [ ]:
# used to replace the items in list
# do permanat changes

In [ ]:
r = np.random.randint(1,300,40)

In [ ]:
# before put
r

array([ 53, 281, 149, 207, 146,  94,  44, 279, 278, 182, 131, 196, 288,
        29,  42,  73, 172, 148, 133, 212,  75, 273, 230,   5, 123, 260,
        83, 259, 107, 133, 203,  33, 150, 134,  79, 104, 154,  61, 256,
       117])

In [ ]:
# after put
r

array([ 530, 2810,  149,  207,  146,   94,   44,  279,  278,  182,  131,
        196,  288,   29,   42,   73,  172,  148,  133,  212,   75,  273,
        230,    5,  123,  260,   83,  259,  107,  133,  203,   33,  150,
        134,   79,  104,  154,   61,  256,  117])

In [ ]:
np.put(r,[0,1],[530,2810])

#### np.delete()

In [ ]:
# used to delete items in list

In [ ]:
s = np.arange(15)

In [ ]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.delete(s,[0,2,3,6,1])

array([ 4,  5,  7,  8,  9, 10, 11, 12, 13, 14])

#### set functions()

In [ ]:
# returns numpy array

In [ ]:
t = np.array([1,2,3,4,5])
u = np.array([3,4,5,6,7])

In [ ]:
np.union1d(t,u)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(t,u)

array([3, 4, 5])

In [ ]:
np.setdiff1d(t,u)

array([1, 2])

In [ ]:
np.setdiff1d(u,t)

array([6, 7])

In [ ]:
np.setxor1d(t,u)

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,7)

/tmp/ipython-input-3063205614.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,7)


array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

#### np.clip()

In [ ]:
# bring values in given range
# if value below a_min then value = a_min
# if value below a_max then value = a_max

In [ ]:
v = np.random.randint(1,100,25)

In [ ]:
v

array([74, 90, 55, 29, 63, 93, 11, 89, 69, 22, 69, 58, 98, 70, 88, 65, 64,
        4, 35, 18, 83, 34, 71, 61, 26])

In [ ]:
np.clip(v,a_max=80,a_min=40)

array([74, 80, 55, 40, 63, 80, 40, 80, 69, 40, 69, 58, 80, 70, 80, 65, 64,
       40, 40, 40, 80, 40, 71, 61, 40])

#### homework